"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

import sys

first_term = 0
second_term = 1
curr = first_term + second_term
total = 0

while second_term <= 4000000:
    if (curr % 2 == 0):
        total += curr

    first_term = second_term
    second_term = curr
    curr = first_term + second_term

print("total = {}".format(total))
