"""
https://projecteuler.net/problem=12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import time
import math

import euler_lib


def main():

    n = 500

    start_time = time.process_time()
    triangle, divisors = div(n)
    end_time = time.process_time()

    print("time to calculate: {}".format(end_time - start_time))
    print("triangle: {}".format(triangle))
    print("number of divisors: {}".format(len(divisors)))

def div(n):

    divisors = list()
    tmp = 0

    i = 0
    while len(divisors) < n:
        i += 1

        triangle = euler_lib.get_triangle_number(i)
        divisors = euler_lib.get_factors(triangle)
    
    return triangle, divisors

main()
