"""
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

fib_1 = 0
fib_2 = 1
fib_curr = fib_1 + fib_2
even_sum = 0

while fib_2 <= 4000000:
    if (fib_curr % 2 == 0):
        even_sum += fib_curr

    fib_1 = fib_2
    fib_2 = fib_curr
    fib_curr = fib_1 + fib_2

print("total: {}".format(even_sum))
