def main():

    n = 4000000

    f1 = 1
    f2 = 1
    fn = f1 + f2
    total = 0

    while f2 <= n:
        if fn % 2 == 0:
            total += fn

        f1 = f2
        f2 = fn
        fn = f1 + f2

    return total

def description():

    desc = """
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
    print(desc, end="")
pe_name = "EVEN FIBONACCI NUMBERS"
if __name__ == "__main__":
    main()
